---
version: "2.0"

services:
  web:
    image: bwo0877hpnza/mb_base_api:0.1
    env:
    expose:
      - port: 5000
        as: 5000
        to:
          - global: true
      - port: 2222
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 20

deployment:
  web:
    dcloud:
      profile: web
      count: 1